# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:35
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161013_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('mov', 'Pel\xedcula'), ('ser', 'Serie')], max_length=3),
        ),
    ]
