# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161014_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='quality',
            field=models.CharField(choices=[('1080p', '1080p'), ('720p', '720p')], default='1080p', max_length=5),
            preserve_default=False,
        ),
    ]
