# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20161015_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
