# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_entry_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('entry', 'quality')]),
        ),
    ]
