# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20161017_0435'),
        ('base', '0009_auto_20161016_1837'),
    ]

    operations = [
    ]
