# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_merge_20161018_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_anime',
            field=models.BooleanField(default=False),
        ),
    ]
