# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_media_trakt_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='api',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='entry',
            name='episode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='season',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
