# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20161026_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Media')),
            ],
        ),
    ]
