# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_mainmedia'),
        ('base', '0014_auto_20161117_1509'),
    ]

    operations = [
    ]
