# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_merge_20170127_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
    ]
