# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20170127_2240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('media', 'episode', 'season')]),
        ),
    ]
