# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='base.Resource'),
        ),
    ]
